-- BGE-M3 emits 1024-dimensional vectors. Preserve OCR/sparse-vector rows while
-- invalidating dense vectors generated by the previous embedding model.
DROP INDEX IF EXISTS "vectors_dense_vector_hnsw_idx";

ALTER TABLE "vectors"
  ALTER COLUMN "dense_vector" TYPE vector(1024)
  USING NULL::vector(1024);

CREATE INDEX "vectors_dense_vector_hnsw_idx"
  ON "vectors" USING hnsw ("dense_vector" vector_cosine_ops);
